#!/bin/bash

# to control if an usb soundcard is present, if not, tell the user that we will not play


# this checks if hardware side is an usb card present

#if cat /proc/asound/cards | grep -q 'USB'
#then
#  echo "sound card is present, play"
     
#else
#  echo "usdb not presetn witch soundcard to jack or hdmi"
 
#fi
#exit 0



# this checks if omxplayer is set to alsa/usb

if cat /var/www/sync/startmaster | grep -q 'alsa'
then
  echo "alsa USB"
else
  echo "jack/hdmi"
fi




# now we need somehow to combine this to:
# if omxplayer is set to alsa and usb is present = play
# if omxplayer is set to alsa and usb is not present trow an error message and exit
# if omxplyer is not set to alsa, just play
