#!/bin/bash

#customfunction1
#this script launches the mapper and kills it after given time (seconds)

TIME=120
print "will kill after $TIME seconds"
#kill all running tasks
/var/www/sync/stopall &


#launch mapper
/var/www/sync/launchmapper &

sleep $TIME

/var/www/sync/stopall &
