#!/bin/bash

#customfunction2
#this will start the random audio player and trigger a relais
#after PLAYTIME it will stop the audio, after RELAISTIME turno off the relais to off
#after KILLTIME will stop everything

PLAYTIME=
RELAISTIME=
KILLTIME=
