#!/bin/bash

#kill all running tasks
#/var/www/sync/stopall

#Set mapper slideshow to proportional

sudo sed -ri 's@(<ResizeOption>).*(</ResizeOption>)@\1Native\2@' '/home/pvj/openFrameworks/addons/ofxPiMapper/example_fbo-sources/bin/data/magslideshow_settings.xml'
