#!/bin/bash

#this script exports the mapper settings to /media/internal/mappersettings.xml
#made for PVJ

#Killall tasks:

sudo /var/www/sync/stopall

sleep 0.5

sudo cp /media/internal/mappersets/mappersetting5.xml /home/pvj/openFrameworks/addons/ofxPiMapper/example_basic/bin/data/ofxpimapper.xml
sudo cp /media/internal/mappersets/mappersetting5.xml /home/pvj/openFrameworks/addons/ofxPiMapper/example_camera/bin/data/ofxpimapper.xml
sudo cp /media/internal/mappersets/mappersetting5.xml /home/pvj/openFrameworks/addons/ofxPiMapper/example_fbo-sources/bin/data/ofxpimapper.xml
sudo cp /media/internal/mappersets/mappersetting5.xml /home/pvj/openFrameworks/addons/ofxPiMapper/example_remote-server/bin/data/ofxpimapper.xml


sleep 0.5

#preload all the fake keyboard stuff
/opt/fsaysuinput &

#The below commands are only used if no mouse is connected,
#if this happens,keep in mind to change /dev/input/event1 to /dev/input/event0
mkdir /dev/input/by-id/
mkdir /dev/input/by-path/

#ln -s /dev/input/event0 /dev/input/by-id/usb-046a_0023-event-kbd
#ln -s /dev/input/event0 /dev/input/by-path/platform-bcm2708_usb-usb-0:1.2.4:1.0-event-kbd


ln -s /dev/input/event1 /dev/input/by-id/usb-046a_0023-event-kbd
ln -s /dev/input/event1 /dev/input/by-path/platform-bcm2708_usb-usb-0:1.2.4:1.0-event-kbd

#open the mapper, this is for the basic one
/home/pvj/openFrameworks/addons/ofxPiMapper/example_basic/./bin/example_basic -f  > /dev/null 2>&1 &

