#!/bin/bash

#stopall
	sudo /var/www/sync/stopall > /dev/null 2>&1

#set to audio hdmi
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmaster &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmasterusb01 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmasterusb02 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmasterusb &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmasterone &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmaster01 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmaster02 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmaster03 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmaster04 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmaster05 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmaster06 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmaster07 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmaster08 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmaster09 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmaster10 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmaster11 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmaster12 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmaster13 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmaster14 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmaster15 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmaster16 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmasterone01 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmasterone02 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmasterone03 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmasterone04 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmasterone05 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmasterone06 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmasterone07 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmasterone08 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmasterone09 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmasterone10 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmasterone11 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmasterone12 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmasterone13 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmasterone14 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmasterone15 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmasterone16 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmasterone17 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmasterone18 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmasterone19 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmasterone20 &
#audio
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startaudio &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startaudio01once &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startaudio02once &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startaudio03once &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startaudiousb &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startaudiostream &
#looped without sync
	sudo sed -ri 's/PLAYER=.*/PLAYER="omxplayer -o hdmi"/' /var/www/sync/startlesshelper &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startless01 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startless02 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startless03 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startless04 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startless05 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startless06 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startless07 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startless08 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startless09 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startless10 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startless11 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startless12 &
#special looped without sync without stop
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startlesser01 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startlesser02 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startlesser03 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startlesser04 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startlesser05 &
#once without sync less
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startlessonce01 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startlessonce02 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startlessonce03 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startlessonce04 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startlessonce05 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startlessonce06 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startlessonce07 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startlessonce08 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startlessonce09 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startlessonce10 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startlessonce11 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startlessonce12 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startlessonce13 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startlessonce14 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startlessonce15 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startlessonce16 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startlessonce17 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startlessonce18 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startlessonce19 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startlessonce20 &	
#set the audio on dmx scripts
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startdmxplaybackvid01 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startdmxplaybackvid02 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startdmxplaybackvid03 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startdmxplaybackvid04 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startdmxplaybackvid05 &
#set on dmx audio player mpg123
	sudo amixer cset numid=3 0 > /dev/null 2>&1 &
	sudo sed -ri 's/-o [[:graph:]]+/-o alsa:hw:0,0/' /var/www/sync/startdmxplaybackaudio01 &
	sudo sed -ri 's/-o [[:graph:]]+/-o alsa:hw:0,0/' /var/www/sync/startdmxplaybackaudio01b &
	sudo sed -ri 's/-o [[:graph:]]+/-o alsa:hw:0,0/' /var/www/sync/startdmxplaybackaudio01once &
	sudo sed -ri 's/-o [[:graph:]]+/-o alsa:hw:0,0/' /var/www/sync/startdmxplaybackaudio02 &
	sudo sed -ri 's/-o [[:graph:]]+/-o alsa:hw:0,0/' /var/www/sync/startdmxplaybackaudio02b &	
	sudo sed -ri 's/-o [[:graph:]]+/-o alsa:hw:0,0/' /var/www/sync/startdmxplaybackaudio03 &
	sudo sed -ri 's/-o [[:graph:]]+/-o alsa:hw:0,0/' /var/www/sync/startdmxplaybackaudio03b &
	sudo sed -ri 's/-o [[:graph:]]+/-o alsa:hw:0,0/' /var/www/sync/startdmxplaybackaudio04 &
	sudo sed -ri 's/-o [[:graph:]]+/-o alsa:hw:0,0/' /var/www/sync/startdmxplaybackaudio04b &	
	sudo sed -ri 's/-o [[:graph:]]+/-o alsa:hw:0,0/' /var/www/sync/startdmxplaybackaudio05 &
#set on beacon
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startlessonce01b &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startlessonce02b &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startlessonce03b &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startlessonce04b &
#set for testtone
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/testtone &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/testtoneleft &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/testtoneright &
#set the audio for midi script
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmididmxvideoplay01 &
	sudo sed -ri 's/-o [[:graph:]]+/-o hdmi/' /var/www/sync/startmididmxaudioplay01 &
#set on pir 
    sudo sed -ri "/^OMXPLAYER = \['omxplayer', '-o',/c\OMXPLAYER = ['omxplayer', '-o', 'hdmi', '--no-osd']" /var/www/sync/startpir1.py &
#install mapper with hdmi support
	sudo rm -r /home/pvj/openFrameworks/addons/ofxPiMapper/
	sudo unzip /var/www/sync/mapper_all_hdmi.zip -d /
	sudo ln -s /media/internal/video /home/pvj/openFrameworks/addons/ofxPiMapper/example_basic/bin/data/sources/videos
	sudo ln -s /media/internal/images /home/pvj/openFrameworks/addons/ofxPiMapper/example_basic/bin/data/sources/images
	sudo ln -s /media/internal/video /home/pvj/openFrameworks/addons/ofxPiMapper/example_fbo-sources/bin/data/sources/videos
	sudo ln -s /media/internal/images /home/pvj/openFrameworks/addons/ofxPiMapper/example_fbo-sources/bin/data/sources/images
	sudo ln -s /media/internal/video /home/pvj/openFrameworks/addons/ofxPiMapper/example_remote-server/bin/data/sources/videos
	sudo ln -s /media/internal/images /home/pvj/openFrameworks/addons/ofxPiMapper/example_remote-server/bin/data/sources/images
