#!/bin/bash
#setting the sense to high 12

sed -i '/^triggers =/c\triggers = 12 # set how many triggers until action' /var/www/sync/startpir1.py
sed -i '/^triggers =/c\triggers = 12 # set how many triggers until action' /var/www/sync/startpirtest.py
