#!/bin/bash
#setting the sense to low 30


sed -i '/^triggers =/c\triggers = 30 # set how many triggers until action' /var/www/sync/startpir1.py
sed -i '/^triggers =/c\triggers = 30 # set how many triggers until action' /var/www/sync/startpirtest.py
