#!/bin/bash

# Set the delay value in seconds, use 0.1 for smaller numbers
AUDIODELAY=1

#kill all runing tasks to be safe
/var/www/sync/stopall

#create a file so we know to keep looping
touch /tmp/dmxloop

#start the loop process
while [ -f /tmp/dmxloop ]
do

#for debugging only
#echo start looping
  
#kill omxplayer, audioplayer and dmx player
  sudo /var/www/sync/omxkill > /dev/null 2>&1
  sudo killall -9 /usr/bin/mpg123 > /dev/null 2>&1
  sudo killall -9 ola_recorder > /dev/null 2>&1

  #play dmx sequence01 -i 1 means play once, -i 0 loops forever
  sudo ola_recorder --no-verify-playback -i 1 -p /media/internal/dmx/show03 > /dev/null &

  #sleep, used to create the dealy
  sleep ${AUDIODELAY}

  #play audio 01
  #/usr/bin/omxplayer -o both /media/internal/audio/03* > /dev/null 2>&1 
  /usr/bin/mpg123 -o alsa:hw:0,0 -f -22000 /media/internal/audio/03* > /dev/null 2>&1
done

exit