#!/bin/bash

ENABLE=NO
TRIGGERDELAY=90

###################
#kill beacon scanner
#/var/www/sync/stopbeacon > /dev/null 2>&1
sudo kill $(pgrep -f 'python3 /var/www/sync/bluetooth_beacon.py') > /dev/null 2>&1 &
sleep 0.5

#kill all running tasks
/var/www/sync/stopall > /dev/null 2>&1
##################

#check if TRIGGERDELAY is enabled or disabled

echo "Start scanner while playing:" $ENABLE 
echo "TRIGGERDELAY time is" $TRIGGERDELAY


if [[ $ENABLE == "YES" ]]; then
/usr/bin/omxplayer --no-osd -o both /media/internal/video/02* &
echo "omxplayer with & sign"
fi


if [[ $ENABLE == "NO" ]]; then
/usr/bin/omxplayer --no-osd -o both /media/internal/video/02* 
echo "omxplayer no additions, waited until file finished"
fi


# sleep before starting beacon scanner again, only when TRIGGERDELAY is enabled
if [[ $ENABLE == "YES" ]]; then
echo "sleep before rescan" $TRIGGERDELAY
sleep $TRIGGERDELAY
fi



#when video has finished, check if scannerfile /tmp/bluetooth_beacon exists, then do
if [ -f /tmp/bluetooth_beacon ]
then
    echo file found, scan again:
    #start still image    
    sudo fbi -T 1 -a -noverbose /media/internal/pir/stillshot.png > /dev/null 2>&1 
    #start beacon scanner again
    sudo python3 /var/www/sync/bluetooth_beacon.py > /dev/null 2>&1 &
else
    #stop scanner and exit all processes
    echo no file found, stopping everything
    sudo kill $(pgrep -f 'python3 /var/www/sync/bluetooth_beacon.py') > /dev/null 2>&1 &
    /var/www/sync/stopall > /dev/null 2>&1
    echo all tasks stopped
fi

echo ended startlessonce0*b

exit 0
