#!/bin/bash
#kill all running tasks
/var/www/sync/stopall

#start video as master with node-omxplayer-sync (must be pocketvj-100)

#sudo -H -u pvj bash -c "node /home/pvj/node-omxplayer-sync/omx-sync-wifi.js /media/internal/video/wifisync.mp4"
su - pvj -c "node /home/pvj/node-omxplayer-sync/omx-sync-wifi.js /media/internal/video/wifisync.mp4"