#!/bin/bash

#kill all running tasks 
/var/www/sync/stopall

#write to autostart that feh shall start
sudo cp /var/www/sync/slidestartupmanual /home/pvj/.config/lxsession/LXDE/autostart


#start x and run feh
su -s /bin/bash -c startx pvj &
