#!/bin/bash

#kill all running tasks
/var/www/sync/stopall > /dev/null 2>&1
sleep 1

#start audioplayer:

#enable as alternative, no sync!!
#mpg321 -l 0 /media/internal/audio/* > /dev/null 2>&1 & echo $! &

#enable for mp3
/usr/bin/omxplayer-sync -lu -o both /media/internal/audio/*.mp3 > /dev/null 2>&1 & echo $! &


#enable for wav
#/usr/bin/omxplayer-sync -lu -o both /media/internal/audio/*.wav > /dev/null 2>&1 & echo $! &

