#!/bin/bash
#startdmx playback


#kill all running tasks
/var/www/sync/stopall

if [ -f /etc/openvpn/pocketvj.remote.conf ] && [ "$(md5sum < /proc/device-tree/hat/product)" = "33e26e96aeb252a3e1374ca44ad684a2  -" ]
        
        then
        # plays only once forever
        sudo ola_recorder --no-verify-playback -i 1 -p /media/internal/dmx/show01 &
        echo "playback show01"
else
  echo "this is not PocketVJ Exhibtion, aborting"
  exit 0
fi




