#!/bin/bash

#kill beacon scanner
sudo kill $(pgrep -f 'python3 /var/www/sync/bluetooth_beacon.py') > /dev/null 2>&1 &
sleep 0.5

#kill all running tasks
/var/www/sync/stopall > /dev/null 2>&1
sleep 0.5

#play dmx sequence

if [ -f /etc/openvpn/pocketvj.remote.conf ] && [ "$(md5sum < /proc/device-tree/hat/product)" = "33e26e96aeb252a3e1374ca44ad684a2  -" ]
        
        then
        # plays once
        sudo ola_recorder --no-verify-playback -i 1 -p /media/internal/dmx/show01 
        echo "playback show01 once"
        #start beacon scanner again
        sudo python3 /var/www/sync/bluetooth_beacon.py > /dev/null 2>&1 &
else
  echo "this is not PocketVJ Exhibition, aborting"
  exit 0
fi


#when dmx file has finished, check if scannerfile /tmp/bluetooth_beacon exists, then do
if [ -f /tmp/bluetooth_beacon ]
then
    echo file found, scan again:
    #start beacon scanner again
    sudo python3 /var/www/sync/bluetooth_beacon.py > /dev/null 2>&1 &
else
    #stop scanner and exit all processes
    echo no bluetooth scan file found, stopping everything
    sudo kill $(pgrep -f 'python3 /var/www/sync/bluetooth_beacon.py') > /dev/null 2>&1 &
    /var/www/sync/stopall > /dev/null 2>&1
    echo all tasks stopped
fi

echo ended startdmxplaybackonce0*b
#give an exit everything good when finished
exit 0

