#!/bin/bash

# Set the delay value in seconds, use 0.1 for smaller numbers
AUDIODELAY=1

#kill all runing tasks to be safe
/var/www/sync/stopall > /dev/null 2>&1


#play dmx sequence01 -i 1 means play once, -i 0 loops forever
sudo ola_recorder --no-verify-playback -i 1 -p /media/internal/dmx/show02 > /dev/null &

#sleep, used to create the delay
sleep ${AUDIODELAY}

#play audio 01
#/usr/bin/omxplayer -o alsa:hw:0,0 /media/internal/audio/01* > /dev/null 2>&1
/usr/bin/mpg123 -o alsa:hw:0,0 -f -22000 /media/internal/audio/02* > /dev/null 2>&1


exit 0
