#!/bin/bash

#kill beacon scanner
/var/www/sync/stopbeacon
sleep 0.5

#kill all running tasks
/var/www/sync/stopall > /dev/null 2>&1

#play video01 without sync
/usr/bin/omxplayer --no-osd -o both /media/internal/video/01* 

#start stillshot after video is finished
sudo fbi -T 1 -a -noverbose /media/internal/pir/stillshot.png > /dev/null 2>&1 

#start beacon scanner again
sudo python3 /var/www/sync/bluetooth_beacon.py > /dev/null 2>&1 &

