#!/bin/bash

#kill all running tasks exept .mp3 player
/var/www/sync/stopall

#initalize faked keyboard

/opt/fsaysuinput &

#The below commands are only used if no mouse is connected, 
#if this happens,keep in mind to change /dev/input/event1 to /dev/input/event0
mkdir /dev/input/by-id/
mkdir /dev/input/by-path/

ln -s /dev/input/event0 /dev/input/by-id/usb-046a_0023-event-kbd
ln -s /dev/input/event0 /dev/input/by-path/platform-bcm2708_usb-usb-0:1.2.4:1.0-event-kbd

#write to autostart that feh shall start
sudo cp /var/www/sync/xsessionpdf /home/pvj/.config/lxsession/LXDE/autostart

#start x as pvj user
#sudo su -s /bin/bash -c startx pvj &
sudo su -c startx -s /bin/sh pvj &
