#!/bin/bash

ENABLE=NO
TRIGGERDELAY=90
AUDIODELAY=0

#######################
#Essential things
######################
#kill beacon scanner
echo "beacon found, kill scanner"
sudo kill $(pgrep -f 'python3 /var/www/sync/bluetooth_beacon.py') > /dev/null 2>&1 &
sleep 0.5
echo "scanner killed"
#kill all running tasks
/var/www/sync/stopall > /dev/null 2>&1
echo "all tasks stopped"
echo "sleep 1"
sleep 0.5
#echo "manually kill all dmx sequenced again"
#sudo killall -9 ola_recorder > /dev/null 2>&1 &
#echo "set dmx blackout"
#sudo /var/www/sync/setdmxblackout &
######################


#play dmx sequence
if [ -f /tmp/bluetooth_beacon ] && [ "$(md5sum < /proc/device-tree/hat/product)" = "33e26e96aeb252a3e1374ca44ad684a2  -" ]

        then
        #check if TRIGGERDELAY is enabled or disabled
	echo "Start scanner while playing:" $ENABLE 
	echo "TRIGGERDELAY time is" $TRIGGERDELAY

		if [[ $ENABLE == "YES" ]]; then
		sudo ola_recorder --no-verify-playback -i 1 -p /media/internal/dmx/show04 &
        #delay until audio starts
        sleep ${AUDIODELAY}
		echo "startaudioplayer"
	        $(/usr/bin/omxplayer -o both /media/internal/audio/04* ) & 
		echo "dmxplaying and restarting scanner in" $TRIGGERDELAY
		sleep $TRIGGERDELAY
		fi


		if [[ $ENABLE == "NO" ]]; then
		sudo ola_recorder --no-verify-playback -i 1 -p /media/internal/dmx/show04 &
        sleep ${DELAY}
	        /usr/bin/omxplayer -o both /media/internal/audio/04* > /dev/null 2>&1
		echo "dmxplaying, waited until audio finished"
		sudo /var/www/sync/setdmxblackout &
		fi

        echo "start beacon scanner again"
        sudo python3 /var/www/sync/bluetooth_beacon.py > /dev/null 2>&1 &
        echo "beacon scanner is running"

else
  echo "this is not PocketVJ Exhibition, aborting"
  echo "or"
  echo "no bluetooth scan loop file found, stopping everything"
    sudo kill $(pgrep -f 'python3 /var/www/sync/bluetooth_beacon.py') > /dev/null 2>&1 &
    sudo /var/www/sync/stopall > /dev/null 2>&1
    echo "all tasks stopped"
fi

echo "ended startdmxplaybackaudio0*b"

exit 0

