#!/bin/bash

#kill all running tasks
/var/www/sync/stopall > /dev/null 2>&1

#start audioplayer:

#enable as alternative, no sync!!
#mpg321 -l 0 /media/internal/audio/* > /dev/null 2>&1 & echo $! &
# -f sets the volume, max is:32768  but dont go higher than 22000
#mpg123 -f -22000 /media/internal/audio/* 

#enable for mp3
/usr/bin/omxplayer-sync -m -o local /media/internal/audio/03*.mp3 > /dev/null 2>&1 & echo $! &


#enable for wav
#/usr/bin/omxplayer-sync -mu -o both /media/internal/audio/*.wav > /dev/null 2>&1 & echo $! &
