#!/bin/bash

#kill all running tasks is disabled!!!
#/var/www/sync/stopall

#play video 05 seamless looped without sync

/usr/bin/omxplayer --loop --no-osd -o both /media/internal/video/05* > /dev/null 2>&1 & echo $! &

