#!/bin/bash


#stop everything

sudo /var/www/sync/stopall > /dev/null 2>&1
sudo /var/www/sync/stopbeacon > /dev/null 2>&1

# starts the countdown script


/usr/bin/python3 /var/www/sync/countdown.py &


exit 0 




