#!/bin/bash

# Set the delay value in seconds, use 0.1 for smaller numbers
DELAY=0

#kill all runing tasks to be safe
/var/www/sync/stopall

#create a file so we know to keep looping
touch /tmp/dmxloop

#start the loop process
while [ -f /tmp/dmxloop ]
do
  #kill omxplayer and dmx player, to be safe
  sudo /var/www/sync/omxkill > /dev/null 2>&1
  sudo killall -9 ola_recorder > /dev/null 2>&1

  #play dmx sequence01 -i 1 means play once, -i 0 loops forever
  sudo ola_recorder --no-verify-playback -i 1 -p /media/internal/dmx/show01 > /dev/null &

  #sleep, used to create the dealy
  sleep ${DELAY}

  #play audio 01
  /usr/bin/omxplayer -o both /media/internal/video/01* > /dev/null 2>&1 

done
echo ended looping
#is exit needed?
exit
