#!/bin/bash

#kill beacon scanner
/var/www/sync/stopbeacon
sleep 0.5

#kill all running tasks
/var/www/sync/stopall > /dev/null 2>&1

if [ -f /etc/openvpn/pocketvj.remote.conf ] && [ "$(md5sum < /proc/device-tree/hat/product)" = "33e26e96aeb252a3e1374ca44ad684a2  -" ]

        then
        # plays once
        sudo ola_recorder --no-verify-playback -i 1 -p /media/internal/dmx/show02 
        echo "playback show01 once"
        #start beacon scanner again
        sudo python3 /var/www/sync/bluetooth_beacon.py > /dev/null 2>&1 &
else
  echo "this is not PocketVJ Exhibition, aborting"
  exit 0
fi

