#!/bin/bash

#kill dmx loop file
sudo rm -rf /tmp/dmxloop &

#kill omxplayer less loop file, player will be killed later on
sudo kill $(pgrep 'startlesshelper')  > /dev/null 2>&1 &

#kill xserver
sudo killall -9 /usr/bin/lxsession > /dev/null 2>&1 &

#kill Xvfb virtual framebuffer for qlc plus
sudo pkill Xvfb > /dev/null 2>&1 &

#kill videoplayer
sudo /var/www/sync/omxkill > /dev/null 2>&1 &

#kill mapper
sudo killall -9 /home/pvj/openFrameworks/addons/ofxPiMapper/example_basic/./bin/example_basic > /dev/null 2>&1 &
sudo killall -9 /home/pvj/openFrameworks/addons/ofxPiMapper/example_camera/./bin/example_camera > /dev/null 2>&1 &
sudo killall -9 /home/pvj/openFrameworks/addons/ofxPiMapper/example_fbo-sources/./bin/example_fbo-sources > /dev/null 2>&1 &
sudo killall -9 /home/pvj/openFrameworks/addons/ofxPiMapper/example_remote-server/./bin/example_remote-server > /dev/null 2>&1 &

#kill Syphon
sudo killall -9 /usr/bin/TCPSClient.bin > /dev/null 2>&1 &

#kill clock, audioplayer and imageplayer
sudo killall -9 tty-clock > /dev/null 2>&1 &
sudo killall -9 mpg321 > /dev/null 2>&1 &
sudo killall -9 mpg123 > /dev/null 2>&1 &
sudo killall -9 feh > /dev/null 2>&1 &
sudo /var/www/sync/testscreenoff > /dev/null 2>&1 &

#kill countdown

#sudo kill $(pgrep 'countdown.py') > /dev/null 2>&1 &
sudo kill $(pgrep -f '/usr/bin/python3 /var/www/sync/countdown.py') > /dev/null 2>&1 &

#kill webcam lifefeed
sudo kill $(pgrep -f '/usr/bin/python /var/www/sync/camerastream.py') > /dev/null 2>&1 &
sudo kill $(pgrep -f '/usr/bin/python /var/www/sync/camerastreamhsv.py') > /dev/null 2>&1 &

#kill beacon
#sudo kill $(pgrep -f 'python3 /var/www/sync/bluetooth_beacon.py') > /dev/null 2>&1 &

#kill kenburns imageplayer
#sudo pkill -9 -f Slideshow_3d.py > /dev/null 2>&1
sudo pkill -9 -f PictureFrame.py > /dev/null 2>&1 &

#kill overlay and softedge
sudo killall -9 /home/pvj/raspidmx/pngview/./pngview /media/internal/images/overlay.png > /dev/null 2>&1 &
sudo killall -9 /home/pvj/raspidmx/pngview/./pngview /media/internal/images/softedge* > /dev/null 2>&1 &

#kill fake keyboard:
sudo killall -9 fsaysuinput > /dev/null 2>&1 &

#Kill dmx player/recorder
sudo killall -9 ola_recorder > /dev/null 2>&1 &

#set all dmx to 0 = blackout
sudo /var/www/sync/setdmxblackout > /dev/null 2>&1 &

#kill camerafeed
sudo killall -9  /usr/bin/raspivid > /dev/null 2>&1 &

#kill puredata
sudo killall -9 /usr/bin/pd-extended > /dev/null 2>&1 &

#kill python pir only
sudo kill $(pgrep -f 'python /var/www/sync/startpir1.py') > /dev/null 2>&1 &

#kill python buttons only, this would kill it everytime, default is commented out!
#sudo kill $(pgrep -f 'python3 /var/www/sync/startbuttons.py') > /dev/null &

#kill python random_video_trigger only
sudo kill $(pgrep -f 'python /var/www/sync/random_video_trigger.py') > /dev/null &

#kill midi recorder
sudo kill $(pgrep 'arecordmidi') > /dev/null 2>&1 &

#kill midi player
sudo kill $(pgrep 'aplaymidi') > /dev/null 2>&1 &

#kill all python scripts
# this destroyes also usefull things like midi2command
#sudo killall python > /dev/null 2>&1

#kill top command
#sudo killall -9 top

#overwrite screen with all black, tri to avoid in future
#sudo /var/www/sync/clearscreen.sh > /dev/null &

#overwrite tty1 -tty3 with black to get rid of the clock
sudo printf "\033c" > /dev/tty1 2>&1 &
sudo printf "\033c" > /dev/tty2 2>&1 &
sudo printf "\033c" > /dev/tty3 2>&1 &

#overwrite screen to black, also fbi
dd if=/dev/zero of=/dev/fb0 > /dev/null 2>&1
dd if=/dev/zero of=/dev/fb0 > /dev/null 2>&1

#make dmx show files writeable
sudo chmod 777 -R /media/internal/dmx > /dev/null 2>&1 &

#clear log
sudo rm /var/www/*.log > /dev/null 2>&1 &

#without sleep things would kill themself
sleep 1

exit
